from django.urls import path
from admin_panel import views

urlpatterns=[
    path('index_page/',views.index_page,name="index_page"),
    path('add_service_category/',views.add_service_category,name="add_service_category"),
    path('save_category/',views.save_category,name="save_category"),
    path('display_service_category/',views.display_service_category,name="display_service_category"),
    path('display_service_category/',views.display_service_category,name="display_service_category"),
    path('edit_service_category/<int:c_id>/',views.edit_service_category,name="edit_service_category"),
    path('update_service_category/<int:c_id>/',views.update_service_category,name="update_service_category"),
    path('delete_service_category/<int:c_id>/',views.delete_service_category,name="delete_service_category"),
    path('admin_login_page/',views.admin_login_page,name="admin_login_page"),
    path('admin_login/',views.admin_login,name="admin_login"),
    path('admin_logout/',views.admin_logout,name="admin_logout"),
    path('display_donors/',views.display_donors,name="display_donors"),
    path('delete_donors/<int:d_id>/',views.delete_donors,name="delete_donors"),
    path('display_messages/',views.display_messages,name="display_messages"),
    path('display_drivers/',views.display_drivers,name="display_drivers"),
    path('display_requests/',views.display_requests,name="display_requests"),
    path('delete_drivers/<int:d_id>/',views.delete_drivers,name="delete_drivers"),
    path('delete_requests/<int:r_id>/',views.delete_requests,name="delete_requests"),
    path('add_hospitals/',views.add_hospitals,name="add_hospitals"),
    path('save_hospital/',views.save_hospital,name="save_hospital"),
    path('display_hospitals/',views.display_hospitals,name="display_hospitals"),
    path('edit_hospitals/<int:h_id>/',views.edit_hospitals,name="edit_hospitals"),
    path('update_hospital/<int:h_id>/',views.update_hospital,name="update_hospital"),
    path('delete_hospital/<int:h_id>/',views.delete_hospital,name="delete_hospital"),
    path('hospital_staff_signup_page/',views.hospital_staff_signup_page,name="hospital_staff_signup_page"),
    path('hospital_staff_signup/',views.hospital_staff_signup,name="hospital_staff_signup"),
    path('staff_list/',views.staff_list,name="staff_list"),
    path('delete_staff/<int:staff_id>/', views.delete_staff, name="delete_staff"),
    path('bed_bookings/', views.bed_booking_list, name='bed_booking_list'),
    path('bed_booking/delete/<int:booking_id>/', views.delete_bed_booking, name='delete_bed_booking'),

]