# Generated by Django 5.2.8 on 2025-11-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('Phone', models.CharField(blank=True, max_length=15, null=True)),
                ('Password', models.CharField(blank=True, max_length=200, null=True)),
                ('Confirm_password', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
