# Generated by Django 5.2.8 on 2025-11-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_donorregistrationdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorregistrationdb',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorregistrationdb',
            name='Gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='donorregistrationdb',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='donor_images/'),
        ),
        migrations.AddField(
            model_name='donorregistrationdb',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='donorregistrationdb',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
