# Generated by Django 5.2.8 on 2025-11-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_donorregistrationdb_age_donorregistrationdb_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorregistrationdb',
            name='last_donation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorregistrationdb',
            name='system_inactive',
            field=models.BooleanField(default=False),
        ),
    ]
