# Generated by Django 5.2.8 on 2025-12-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_bloodrequest_donornotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorregistrationdb',
            name='life_saved',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
