# Generated by Django 5.2.8 on 2025-12-11 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_donorregistrationdb_life_saved'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField()),
                ('driver_photo', models.ImageField(upload_to='drivers/')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambulance_number', models.CharField(max_length=30, unique=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.ambulancedriver')),
            ],
        ),
    ]
