# Generated by Django 5.2.8 on 2025-12-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_ambulancedriver_ambulance'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulancedriver',
            name='ambulance_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ambulancedriver',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Ambulance',
        ),
    ]
