# Generated by Django 5.2.8 on 2025-12-19 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_ambulancerequest_ambulanceassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulancerequest',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.ambulancedriver'),
        ),
        migrations.AddField(
            model_name='ambulancerequest',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
