# Generated by Django 5.2.8 on 2025-12-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_bed_hospital_bedbooking_bed_hospital_hospitaluser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hospital_images/'),
        ),
    ]
