# Generated by Django 5.2.8 on 2025-12-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_hospital_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
