# Generated by Django 5.2.8 on 2025-12-27 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_hospitalstaff_delete_hospitaluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedbooking',
            name='booking_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
