# Generated by Django 5.2.8 on 2025-12-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_bedbooking_booking_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bedbooking',
            constraint=models.UniqueConstraint(fields=('bed', 'booking_date', 'user'), name='unique_bed_booking_per_user_per_day'),
        ),
    ]
