# Generated by Django 5.2.8 on 2025-12-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_remove_bedbooking_unique_bed_booking_per_user_per_day'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bedbooking',
            constraint=models.UniqueConstraint(fields=('user', 'bed', 'booking_date'), name='unique_bed_booking_per_user_per_day'),
        ),
    ]
