# Generated by Django 5.2.8 on 2025-12-27 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_bedbooking_unique_bed_booking_per_user_per_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BedBooking',
        ),
    ]
