# Generated by Django 5.2.8 on 2025-12-27 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_bedbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BedBooking',
        ),
    ]
