# Generated by Django 5.2.8 on 2025-12-27 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_bedbooking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bedbooking',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='bedbooking',
            name='unique_bed_booking_per_user_per_day',
        ),
    ]
