# Generated by Django 5.2.8 on 2025-12-27 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_alter_bedbooking_options_and_more'),
    ]

    operations = [
    ]
