# Generated by Django 5.2.8 on 2025-12-27 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_remove_duplicate_bedbookings'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bedbooking',
            unique_together={('user', 'bed', 'booking_date')},
        ),
    ]
