# Generated by Django 5.2.8 on 2025-12-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_alter_bedbooking_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedbooking',
            name='beds_required',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
