# Generated by Django 5.2.8 on 2025-12-28 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_bedbooking_beds_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedbooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bedbooking',
            name='bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.bed'),
        ),
        migrations.AlterField(
            model_name='bedbooking',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.hospital'),
        ),
        migrations.AlterField(
            model_name='bedbooking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='bedbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.userregistration'),
        ),
    ]
