# Generated by Django 5.2.8 on 2025-12-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0030_bedbooking_total_price_alter_bedbooking_bed_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bedbooking',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bedbooking',
            name='booking_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bedbooking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bedbooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.RemoveField(
            model_name='bedbooking',
            name='decision_at',
        ),
        migrations.RemoveField(
            model_name='bedbooking',
            name='is_emergency',
        ),
        migrations.RemoveField(
            model_name='bedbooking',
            name='patient_age',
        ),
        migrations.RemoveField(
            model_name='bedbooking',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='bedbooking',
            name='requested_at',
        ),
    ]
